import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { projects,getProject } from "@/data/projects";
import { ProjectArtwork } from "@/components/ui/project-artwork";
import { ProjectGallery } from "@/components/work/project-gallery";
import { ArrowLeft,ArrowRight,ArrowUpRight } from "@/components/ui/icons";

export const dynamicParams=false;
export function generateStaticParams(){return projects.map(({slug})=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const project=getProject((await params).slug); return project?{title:`${project.title} | Kenicmind Concept`,description:project.description}:{title:"Project not found"};}
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const project=getProject(slug);if(!project)notFound();const index=projects.findIndex((item)=>item.slug===slug);const previous=projects[(index-1+projects.length)%projects.length];const next=projects[(index+1)%projects.length];const related=projects.filter((item)=>item.slug!==slug).slice(0,2);return <><article className="case-study"><header className="case-header shell"><p className="eyebrow">Sample case study / {project.category}</p><h1>{project.title}</h1><div className="case-meta"><div><span>Client</span><p>{project.client}</p></div><div><span>Year</span><p>{project.year}</p></div><div><span>Services</span><p>{project.services.join(", ")}</p></div></div></header><div className="shell case-cover"><ProjectGallery project={project}/></div><div className="shell case-copy"><div><p className="kicker">Project introduction</p><p className="case-lead">{project.introduction}</p></div><div><section><h2>The challenge</h2><p>{project.challenge}</p></section><section><h2>Creative direction</h2><p>{project.direction}</p></section></div></div><div className="shell case-gallery">{project.gallery.map((palette,i)=><div key={`${palette}-${i}`} className={`artwork ${palette}`}><div className="art-grid"/><div className="art-word">{i+1}</div><span className="sample-tag">Sample supporting artwork</span></div>)}</div></article><section className="related-work"><div className="shell"><p className="kicker">Related work</p><div className="related-grid">{related.map((item)=><Link key={item.slug} href={`/work/${item.slug}`}><ProjectArtwork project={item} label={item.sampleContent}/><h3>{item.title}</h3></Link>)}</div><div className="project-nav"><Link href={`/work/${previous.slug}`}><ArrowLeft className="icon"/> Previous project<span>{previous.title}</span></Link><Link href={`/work/${next.slug}`}>Next project <ArrowRight className="icon"/><span>{next.title}</span></Link></div></div></section><section className="project-cta"><div className="shell"><h2>Start a similar project.</h2><Link href="/start-project" className="button button--orange">Tell us about it <ArrowUpRight className="icon"/></Link></div></section></>}
