"use client";

import { useState, type FormEvent } from "react";
import { services } from "@/data/services";

type Errors=Record<string,string>;
export function ProjectEnquiryForm() {
  const [errors,setErrors]=useState<Errors>({}); const [state,setState]=useState<"idle"|"loading"|"ready">("idle");
  function submit(event:FormEvent<HTMLFormElement>) { event.preventDefault(); const form=new FormData(event.currentTarget); const next:Errors={}; ["name","email","service","description","consent"].forEach((key)=>{if(!form.get(key))next[key]="This field is required."}); const email=String(form.get("email")||""); if(email&&!/^\S+@\S+\.\S+$/.test(email))next.email="Enter a valid email address."; setErrors(next); if(Object.keys(next).length)return; setState("loading"); window.setTimeout(()=>setState("ready"),500); }
  const error=(name:string)=>errors[name]?<span className="field-error" id={`${name}-error`}>{errors[name]}</span>:null;
  return <form className="enquiry-form" noValidate onSubmit={submit}><div className="form-grid"><label>Full name<input name="name" aria-invalid={!!errors.name} aria-describedby={errors.name?"name-error":undefined}/>{error("name")}</label><label>Email<input name="email" type="email" aria-invalid={!!errors.email} aria-describedby={errors.email?"email-error":undefined}/>{error("email")}</label><label>Phone or WhatsApp<input name="phone" type="tel"/></label><label>Organisation or brand<input name="organisation"/></label><label>Service required<select name="service" defaultValue="" aria-invalid={!!errors.service} aria-describedby={errors.service?"service-error":undefined}><option value="" disabled>Select a service</option>{services.map((service)=><option key={service.slug}>{service.title}</option>)}</select>{error("service")}</label><label>Estimated budget<select name="budget" defaultValue=""><option value="" disabled>Select a range</option><option>To be discussed</option><option>Budget prepared — details in description</option></select></label><label>Preferred deadline<input name="deadline" type="date"/></label><label>How did you hear about Kenicmind?<input name="referral"/></label><label className="full-field">Project description<textarea name="description" rows={6} aria-invalid={!!errors.description} aria-describedby={errors.description?"description-error":undefined}/>{error("description")}</label></div><label className="consent"><input name="consent" type="checkbox"/> <span>I consent to Kenicmind Concept using these details to respond to my enquiry.</span></label>{error("consent")}<button className="button button--orange" disabled={state==="loading"}>{state==="loading"?"Checking enquiry…":"Review enquiry"}</button>{state==="ready"&&<div className="form-notice" role="status"><strong>Your enquiry is ready.</strong><p>Delivery is not connected yet, so nothing has been sent. Submission will be enabled during the backend phase.</p></div>}<p className="form-note">Final enquiry delivery will be connected during the future backend phase.</p></form>;
}
